erDiagram

    my_table {
        integer _pk PK "not null, increment"
        integer nn "not null"
        integer u UK
        text default_s "default: 'some text'"
        integer default_n "default: 1"
        text multiple "not null, default: 'other text'"
    }