erDiagram

    users {
        integer id PK "not null, increment"
        text registered_at "not null, default: `CURRENT_TIMESTAMP`"
        text username UK "not null"
        text bio
        integer has_blue "not null, default: 0"
    }
    followers {
        integer user_id PK, FK "not null"
        integer follows_user_id PK, FK "not null"
    }
    tweets {
        integer id PK "not null, increment"
        text posted_at "not null, default: `CURRENT_TIMESTAMP`"
        text content "not null"
        integer posted_by_id FK "not null"
    }
    likes {
        integer liked_tweet_id PK, FK "not null"
        integer liked_by_id PK, FK "not null"
    }
users ||--o{ followers : "followers_user_id_users_id_fk"
users ||--o{ followers : "followers_follows_user_id_users_id_fk"
users ||--o{ tweets : "tweets_posted_by_id_users_id_fk"
tweets ||--o{ likes : "likes_liked_tweet_id_tweets_id_fk"
users ||--o{ likes : "likes_liked_by_id_users_id_fk"