erDiagram

    users {
        integer id PK "not null, increment"
        integer config_id
    }
    user_config {
        integer id PK "not null, increment"
    }
    items {
        integer id PK "not null, increment"
        integer sold_by_id "not null"
    }
users ||--|| user_config : "user_config-users"
items ||--o{ users : "items-users"