erDiagram

    my_table {
        integer integer
        smallint smallint
        bigint bigint
        serial serial "not null, increment"
        smallserial smallserial "not null, increment"
        bigserial bigserial "increment"
        boolean boolean
        text text
        varchar varchar
        char char
        numeric numeric
        real real
        double_precision double_precision
        json json
        jsonb jsonb
        time time
        timestamp timestamp
        timestamp timestamp_p3
        timestamptz timestamp_wt
        date date
        interval interval
        interval_day interval_day
        interval interval_p3
        my_enum an_enum
        integer_array int_arr
        integer_2d_array int_2d_arr
    }